// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz90Zj3XVG3FUT6RS8eHvsQPW8Fs8n0YY',
    appId: '1:856215003971:web:baa4e281423a8d1247c5f6',
    messagingSenderId: '856215003971',
    projectId: 'week8-ae43e',
    authDomain: 'week8-ae43e.firebaseapp.com',
    storageBucket: 'week8-ae43e.appspot.com',
    measurementId: 'G-PXDZTFKYTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xEv-FbbteKG39PkZqQYcV630mfaYp6g',
    appId: '1:856215003971:android:ccb3c84e75a1d33947c5f6',
    messagingSenderId: '856215003971',
    projectId: 'week8-ae43e',
    storageBucket: 'week8-ae43e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDym1wyrtAGrqvEqbvzfk2qO3rEczK6eFo',
    appId: '1:856215003971:ios:a60af6b0be96137747c5f6',
    messagingSenderId: '856215003971',
    projectId: 'week8-ae43e',
    storageBucket: 'week8-ae43e.appspot.com',
    iosClientId: '856215003971-m1o00tdpmh0i5ec6lapitb363fti9r2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDym1wyrtAGrqvEqbvzfk2qO3rEczK6eFo',
    appId: '1:856215003971:ios:a60af6b0be96137747c5f6',
    messagingSenderId: '856215003971',
    projectId: 'week8-ae43e',
    storageBucket: 'week8-ae43e.appspot.com',
    iosClientId: '856215003971-m1o00tdpmh0i5ec6lapitb363fti9r2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileFirebase',
  );
}
